"""
Collection of constants used thoughout the app
"""

# Default values and constants related to the input Excel file
ALLOWED_DISPERSION_TYPES = ["_stdev", "_vc"]  # Dispersion types (belonging to distribution types) that are allowed in the input Excel file. _stdev=standard deviation, _vc=variance coefficient
ALLOWED_SUFFIXES = ["_mean"] + ALLOWED_DISPERSION_TYPES  # Variable suffixes allowed in the input Excel file
REQUIRED_COLUMNS = {"vak": ['vak_id',
                            'vak_naam',
                            'M_van',
                            'M_tot',
                            'vak_lengte',
                            'mv_achterland_vak',
                            'L_achterland',
                            'c_voorland_mean',
                            'c_voorland_stdev',
                            'c_achterland_mean',
                            'c_achterland_vc'],
                    "uittredepunt": ['vak_id',
                                    'uittredepunt_id',
                                    'uittredepunt_x_coord',
                                    'uittredepunt_y_coord',
                                    'uittredelocatie',
                                    'M_value',
                                    'vak_naam',
                                    'L_intrede',
                                    'L_but',
                                    'L_bit',
                                    'hydra_locatie_id',
                                    'buitenwaterstand',
                                    'mv_exit',
                                    'polderpeil',
                                    'modelfactor_u_mean',
                                    'modelfactor_u_stdev',
                                    'modelfactor_h_mean',
                                    'modelfactor_h_stdev',
                                    'modelfactor_p_mean',
                                    'modelfactor_p_stdev'],
                    "ondergrond_scenario": ['vak_id',
                                            'ondergrondscenario_id',
                                            'ondergrondscenario_naam',
                                            'ondergrondscenario_kans',
                                            'top_zand_mean',
                                            'top_zand',
                                            'gamma_sat_deklaag_mean',
                                            'gamma_sat_deklaag_stdev',
                                            'D_wvp_mean',
                                            'D_wvp_stdev',
                                            'kD_wvp_mean',
                                            'kD_wvp_vc',
                                            'k_wvp_mean',
                                            'd70_mean',
                                            'd70_vc']
                    }
